#!/usr/bin/env bash

export PGHOST="${POSTGRES_HOST}"
export PGPORT="${POSTGRES_PORT}"
export PGUSER="${POSTGRES_USER}"
export PGPASSWORD="${POSTGRES_PASSWORD}"
export PGDATABASE="${POSTGRES_DB}"

URL="https://www.metrostlouis.org/Transit/google_transit.zip"
DIR="gtfs"
FILE="/${DIR}/feed.zip"

mkdir -p "/${DIR}"

curl -L --fail --retry 10 --retry-delay 2 -o $FILE $URL

unzip -o "${FILE}" -d "${DIR}"

npm install -g gtfs-via-postgres
npm exec -- gtfs-to-sql --require-dependencies -- /${DIR}/*.txt | sponge | psql -b

# node /usr/local/lib/node_modules/gtfs-via-postgres/bin/gtfs-via-postgres.js --database-url $DATABASE_URL < $FILE